### ISSUE TITLE
롯데마트 00/00 날짜 타입 지원

### ISSUE THREAD

**Issue by minseoklee128** [miumida/mart_holiday#2]
롯데마트의 경우 아래와 같이 00/00 날짜 형식의 지점인 경우 오류 발생합니다.

{'martStrCd': '459', 'strCd': '00028', 'strNm': '시흥점', 'regionCode': None, 'regionName': None, 'brnchCd': '0100053', 'brnchTypeCd': 'BC0701', 'brnchHldyDivnCd': 'BRC0502', 'oldAddress': '경기 시흥시 대야동542', 'newAddress': '경기 시흥시 비둘기공원7길 38 ', 'repTelNo': '031-599-2800', 'openTime': '10:00', 'closedTime': '23:00', 'brnchRepImg': 'FILE_000000000019838', 'nearStores': [], 'holiDate': '매월 둘째, 넷째주 일요일 (05/23, 06/13)', 'xcoord': '37.4430011', 'ycoord': '126.7920015', 'storeSiteURL': '/branch/bc/main.do?brnchCd=0100053'}

해당 소스를 간단히 수정해봤는데 committer로 등록해주실 수 있을지 문의드립니다.

**Comment by miumida** [comment]
PR해주시면 테스트 후에 커밋하겠습니다~

**Comment by minseoklee128** [comment]
master 외에 브랜치에도 push 권한이 없는 것 같아 별도 repository로 fork 후 merge 요청하였습니다.

확인해보시고 승인 바랍니다.

merge 되면 기존 fork는 삭제하도록 하겠습니다.

**Comment by miumida** [comment]
PR주신거 반영하고 Release 했습니다.
감사합니다.
